<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <AssemblyName>Nels.SemanticKernel.Core</AssemblyName>
	  <RootNamespace>Nels.SemanticKernel</RootNamespace>
	  <TargetFrameworks>net9.0</TargetFrameworks>
	  <EnablePackageValidation>false</EnablePackageValidation>
	  <VersionSuffix>alpha</VersionSuffix>
	  <NoWarn>$(NoWarn);SKEXP0001,SKEXP0010,SKEXP0070,SKEXP0110,CS8632,CS8618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.KernelMemory.Core" Version="0.98.250508.3" />
    <PackageReference Include="Microsoft.ML.Tokenizers" Version="2.0.0-preview.1.25127.4" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.60.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" Version="1.60.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Amazon" Version="1.51.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Google" Version="1.51.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.HuggingFace" Version="1.51.0-preview" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.MistralAI" Version="1.51.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Ollama" Version="1.51.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Onnx" Version="1.51.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Postgres" Version="1.51.0-preview" />
    <PackageReference Include="System.Net.ServerSentEvents" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\" />
  </ItemGroup>

</Project>
